name: CI

on:
  push:
    branches:
      - main
env:
  SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
jobs:
  security-analysis:
    runs-on: ubuntu-latest
  
    steps:
     
      - name: Checkout the code
        uses: actions/checkout@v2
        
      - name: Install Snyk CLI
        run: npm install -g snyk
          
      - name: Authenticate with Snyk  
        run: snyk config set api=${{secrets.SNYK_TOKEN}}
        
      - name: Test for vulnerabilities with Snyk
        run: snyk code test


  docker-configuration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME }}/devopsimage:latest .
        working-directory: .

      - name: Push Docker image to DockerHub
        run: docker push ${{secrets.DOCKERHUB_USERNAME }}/devopsimage:latest
        # Replace your-dockerhub-username and your-image-name with your DockerHub username and the desired image name.
